### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by ana-clara-candida** [CrowdStrike/MISP-tools#107]
I'm getting this error when running `python3 misp-import.py --reports`
Console output: 
`cs-misp-importer.py:31: DeprecationWarning:
As our baseline system is the latest Ubuntu LTS, and Ubuntu LTS 22.04 has Python 3.10 available,
we will officially deprecate python versions below 3.10 on January 1st 2024.
**Please update your codebase.**
  from pymisp import ExpandedPyMISP, MISPObject, MISPEvent, MISPAttribute, MISPOrganisation
INFO:root:Started getting reports from Crowdstrike Intel API and pushing them as events in MISP.
ERROR:root:'NoneType' object is not iterable
Traceback (most recent call last):
  File "cs-misp-importer.py", line 871, in main
    importer.import_from_crowdstrike(settings.init_reports_days_before, settings.init_indicators_days_before,
  File "cs-misp-importer.py", line 796, in import_from_crowdstrike
    self.reportsImporter.process_reports(reports_days_before, self.eventIDS)
  File "cs-misp-importer.py", line 234, in process_reports
    reports = self.intel_api_client.get_reports(start_get_events)
  File "cs-misp-importer.py", line 104, in get_reports
    reports.extend(resp_json.get('resources', []))
TypeError: 'NoneType' object is not iterable
`

**Comment by jshcodes** [comment]
Hi @ana-clara-candida -

Can you confirm your API key has access to the Actors, Reports and Indicators (Falcon Intelligence) scopes?

<img width="860" alt="Screen Shot 2023-04-10 at 10 48 07 AM" src="https://user-images.githubusercontent.com/74007258/230925355-df9e6cd3-6db6-4db5-8897-8a53fc209b38.png">

**Comment by Tyrell20** [comment]
Hi All,
same issue encountered.

`INFO:root:Started getting reports from Crowdstrike Intel API and pushing them as events in MISP.
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.eu-1.crowdstrike.com:443
DEBUG:urllib3.connectionpool:https://api.eu-1.crowdstrike.com:443 "GET /intel/combined/reports/v1/?sort=last_modified_date.asc&filter=last_modified_date%3A%3E1727733600&limit=1000&offset=0 HTTP/1.1" 200 197
ERROR:root:'NoneType' object is not iterable
Traceback (most recent call last):
  File "cs-misp-importer.py", line 872, in main
    settings.init_actors_days_before)
  File "cs-misp-importer.py", line 796, in import_from_crowdstrike
    self.reportsImporter.process_reports(reports_days_before, self.eventIDS)
  File "cs-misp-importer.py", line 234, in process_reports
    reports = self.intel_api_client.get_reports(start_get_events)
  File "cs-misp-importer.py", line 104, in get_reports
    reports.extend(resp_json.get('resources', []))
TypeError: 'NoneType' object is not iterable
`

Permissions re set correctly. Thanks for your help.
