### ISSUE TITLE
'indicators_tags' are not being asserted on Indicator Events or Indicators

### ISSUE THREAD

**Issue by packet-rat** [CrowdStrike/MISP-tools#116]
### 'indicators_tags' are not being asserted on Indicator Events or Indicators

```
; Standard local tags
; You can add additional tags here, and they will be appended to each event created
; Example: reports_tags = ${CrowdStrike:reports_unique_tag},My_Custom_Tag_1,My_Custom_Tag_2

indicators_tags = att:source="Crowdstrike.Indicators"
```

![image](https://user-images.githubusercontent.com/3220193/232459299-3783fa8e-e2e0-4030-99cb-f7d54bca9d6b.png)

**Comment by jshcodes** [comment]
[Here](https://github.com/CrowdStrike/MISP-tools/blob/main/cs_misp_import/helper.py#L52) is where it _should_ be happening...

Will dig into this as part of the next revision.
