### ISSUE TITLE
New Category - Malware Families(?)

### ISSUE THREAD

**Issue by packet-rat** [CrowdStrike/MISP-tools#118]
### We appear to have a new New Category:  Malware Families.
We should make Malware Families a 1st Class Citizen with it's own "Tag" and ingestion/deletion command line parameters

i.e. add it to "Actors", "Reports", and "Indicators" as a top level category.

**Comment by jshcodes** [comment]
Malware Family events are an event type that represents specific groups of indicators, so not exactly a peer to the top level categories but discrete enough that standalone import and delete functionality does seem to make sense. 

Import would still have to be time based, as you only create new Malware Family events if the event doesn't already exist when the import sees an indicator for that family. Delete would be able to remove them en masse (exactly the way they are removed now).

Marking this as a potential enhancement.

**Comment by packet-rat** [comment]
Thanks.  Can we at least get the ability to specify our Tag on the ini file like we do for the other categories?
________________________________

**Comment by jshcodes** [comment]
[Fixes](https://github.com/CrowdStrike/MISP-tools/commit/b881523f04daf88ccab95052e330a8ef01d329ad) for #116 have already been added to the [ver_0.6.9](https://github.com/CrowdStrike/MISP-tools/tree/ver_0.6.9) branch.  These will merge to main at the end of this sprint.

**Comment by jshcodes** [comment]
Merged the `0.6.9` changes (which includes the fix for #116) today. There will be at least one more release as part of this sprint. 😄
