### ISSUE TITLE
Adding custom headers to MISP requests

### ISSUE THREAD

**Issue by AxoniusTK** [CrowdStrike/MISP-tools#119]
Hey,

Is there an option to add custom headers into all requests that goes to MISP?
I need it in order to bypass the WAF authentication on my MISP tenant.

Thanks :)

**Comment by jshcodes** [comment]
At the moment, only `user-agent` can be customized, but this is a good enhancement suggestion.  We're working on the latest revision now, I'll add this one to the punch list.
