### ISSUE TITLE
Publish flag does not work for all Event Types - Malware Events are not Published

### ISSUE THREAD

**Issue by packet-rat** [CrowdStrike/MISP-tools#123]
Passing the command line **-p** argument does not result in Publishing of Malware Family Events.

`screen -d -m  python3 misp_import.py -f -nb -d -v -p --fullmonty`

![image](https://user-images.githubusercontent.com/3220193/233846072-1ef7f3a5-95de-4640-aed0-05175e4fdb76.png)

**Comment by packet-rat** [comment]
Note that the '--fullmonty' in command line above from yesterday is still running.  This could explain the Indicator Events not being published as Indicator ingestions have been looping indefinitely (https://github.com/CrowdStrike/MISP-tools/issues/113)

**Comment by jshcodes** [comment]
Adding this to the current sprint.

**Comment by jshcodes** [comment]
> Note that the '--fullmonty' in command line above from yesterday is still running. This could explain the Indicator Events not being published as Indicator ingestions have been looping indefinitely (#113)

If it's running that long, reduce the indicator time frame down. (Drop it down to a few hours.)

**Comment by packet-rat** [comment]
This is intended to be the first initial load following —obliterate.

It’s currently set to the maximum.  Use case here is to perform the initial bulk load and then drop back.

Do you expect this will eventually complete or will it just run indefinitely?
________________________________

**Comment by jshcodes** [comment]
The maximum is 15 days worth of indicators.  If you are including hashes, that will be several million or more, which would far exceed what you can import in a day.  (Each iteration would also add new indicators, adding to the overall data segment size.)

**Comment by packet-rat** [comment]
FYSA:


; Initial data segment size

; REPORTS - Up to 1 year can be imported

; INDICATORS - Up to 15 days (20220 minutes) can be imported

; ADVERSARIES (Actors) - Up to 730 days (2 years) can be imported

init_reports_days_before = 365

init_indicators_minutes_before = 20220

;init_indicators_minutes_before = 300

init_actors_days_before = 730

The ingestion appeared to eventually complete AFAICT

However, I’m going to significantly reduce everything:


init_reports_days_before = 7

init_indicators_minutes_before = 2880

init_actors_days_before = 7


Patrick Maroney
Principal - Cybersecurity
Chief Security Office
AT&T Services, Inc.


From: Joshua Hiller ***@***.***>
Date: Tuesday, April 25, 2023 at 8:08 AM
To: CrowdStrike/MISP-tools ***@***.***>
Cc: MARONEY, PATRICK ***@***.***>, Author ***@***.***>
Subject: Re: [CrowdStrike/MISP-tools] Publish flag does not work for all Event Types - Malware Events are not Published (Issue #123)

The maximum is 15 days worth of indicators. If you are including hashes, that will be several million or more, which would far exceed what you can import in a day. (Each iteration would also add new indicators, adding to the overall data segment size.)
