### ISSUE TITLE
[ BUG ] Invalid format string

### ISSUE THREAD

**Issue by hariomenkel** [CrowdStrike/MISP-tools#15]
I'm currently trying to run this project but I'm stumbling across some invalid format strings:

C:\Users\*\Downloads\MISP-tools-main>python misp_import.py --all_indicators
ERROR:root:Invalid format string
Traceback (most recent call last):
  File "C:\Users\*\Downloads\MISP-tools-main\misp_import.py", line 188, in main
    importer.import_from_crowdstrike(int(settings["CrowdStrike"]["init_reports_days_before"]),
  File "C:\Users\*\Downloads\MISP-tools-main\cs_misp_import\importer.py", line 121, in import_from_crowdstrike
    self.indicators_importer.process_indicators(indicators_days_before, self.event_ids)
  File "C:\Users\*\Downloads\MISP-tools-main\cs_misp_import\indicators.py", line 80, in process_indicators
    start_get_events = int((datetime.date.today() - datetime.timedelta(indicators_days_before)).strftime("%s"))
ValueError: Invalid format string
Invalid format string

I checked https://strftime.org/ and "%s"  indeed seems to be an invalid format string.

**Comment by jshcodes** [comment]
This should be returning the epoch, like `date +%s` would within a BASH terminal, but Python doesn't _actually support_ that [format string](https://docs.python.org/3/library/datetime.html).

Thank you for pointing this out, we'll get this resolved.
