### ISSUE TITLE
Please remove/obfuscate full API Keys in error/log messages

### ISSUE THREAD

**Issue by packet-rat** [CrowdStrike/MISP-tools#30]
Full API Keys are exposed in error/log messages.  

A standard best-practice is to include a few characters of the  prefix and suffix of an API key.  It is useful to know which key/user is related to a given action and/or failure.  However disclosure of the keys requires diligence and potentially non-trivial efforts to ensure one isn't exposing credentials when posting to ticketing systems, public forums , etc.

**Comment by jshcodes** [comment]
Are you referring to the MISP API key that is returned in their error message when the API is bogged down and returns a 500?

**Comment by packet-rat** [comment]
Interesting observation!  The problematic behavior is coming from pymisp, correct?  If so you can close this if your logs don’t expose API keys.
________________________________

**Comment by jshcodes** [comment]
CrowdStrike API credentials are **_never_** returned in any log message. (In any integration, anywhere that I know of.) 

If you'd like me to override the error output here to hide the MISP key, I'm happy to do so. :smile:

**Comment by packet-rat** [comment]
If you can solve the issue that would be great.  Otherwise I’ll open a ticket with CIRCL (they’re obviously aware as they state to be aware of the exposure in their error messages ;-)
________________________________

**Comment by jshcodes** [comment]
I think I can take care of it by overriding the error response.  I'll poke into this and let you know if I have any issues.  (That might save you're having to wait on their turn around.)

**Comment by jshcodes** [comment]
Figured out where the constant for this was being created and patched it for now. Let us know if you see encounter any other problems.
