### ISSUE TITLE
[RFI] Proper Method for adding our custom Tags?

### ISSUE THREAD

**Issue by packet-rat** [CrowdStrike/MISP-tools#42]
The 'old' method of adding our own tags do not seem to work.

Previously the following entries in the 'ini' file produced the desired outcomes of adding our own internal tags to CrowdStrike Actor, Report, and Indicator Events.

```
reports_tags = att:source="Crowdstrike.Report"
indicators_tags = att:source="Crowdstrike.Indicators"
actors_tags = att:source="Crowdstrike.Actors"
```

**Comment by jshcodes** [comment]
This was impacted by some of the taxonomic updates, and will be resolved as part of the 0.6.3 version.
