### ISSUE TITLE
Reduce impact on MISP BDD by pushing several indicators in the same event 

### ISSUE THREAD

**Issue by nkoziel** [CrowdStrike/MISP-tools#45]
Right now 1 indicator = 1 event on the misp side, any way to change by adding a parameter to push several indicators in a unique event ?

**Comment by packet-rat** [comment]
Agreed!  The 'as-is' in terms of IOC data modeling is unusable for us...

Here's what we'd like to see:

(1)  One Event for each Adversary (where attributable) and or one Event for each Report.  
(2) All of the related IOCs would be in these single Events.  
(3) Any additional new IOCs would be added to the per Adversary/Report Events,  
(4) Any additional sightings/assertions for an existing IOCs would merely update the built-in Attribute First/Last Seen.
(5) In addition, any new contextual assertions would be added to existing IOCs (as properties in a Custom Object or as Tagging assertions/de-assertions).

**Comment by jshcodes** [comment]
Hi everyone!

We are focusing on this issue in our next sprint (v0.6.4) and will be testing events that aggregate unrelated indicators by malware family.  We also plan to address #42, and several of the pending enhancement requests.

The 0.6.4 branch should post early this week, let us know if you have any questions or feedback.

**Comment by AlfonsoCom** [comment]
But already now I see that a page of indicators is loaded from an API query, and these are all pushed in one event. So isn't this issue already solved?
