### ISSUE TITLE
Duplicative Adversary Records Are Created

### ISSUE THREAD

**Issue by packet-rat** [CrowdStrike/MISP-tools#46]
Multiple duplicate MISP Events are created for the same Adversary:

![image](https://user-images.githubusercontent.com/3220193/186986459-ff5cc406-b7fa-426f-8898-75652da21b1e.png)
These are evidently duplicated on each run of --adversary

**Comment by jshcodes** [comment]
I can't recreate this with the most recent version (the event.info field is compared, with the update being skipped on a match.)  I'm worried there's confusion across the disparate branches.  Working on aligning these to main and then will ask you to retest.

**Comment by packet-rat** [comment]
Any estimate on when everything will be aligned to main?

**Comment by packet-rat** [comment]
In the meantime which branch should I be using?

**Comment by jshcodes** [comment]
> In the meantime which branch should I be using?

ver_0.6.2

I'll get this PR put together and reviewed shortly.

**Comment by jshcodes** [comment]
Hi @packet-rat -

This PR is merged.  Please update from the main branch, retry adversary import (while adversaries already exist within the MISP instance), and let us know if you're still seeing duplicates?

Thank you! 🙇

**Comment by jshcodes** [comment]
Closing as resolved in v0.6.3.  Please reopen this ticket if you encounter this issue again.

**Comment by packet-rat** [comment]
No problem.  I’m happy to reload to ensure we are all working from a common baseline.   I suggest that this version/lineage information be annotated in the ‘opening’ Information log entries (I think I created a ticket for the version in beginning of logs [vs. buried in the Banner…]

Patrick Maroney
Principal - Cybersecurity
Chief Security Office
Office: 732.615.5287 | Cell: 609.678.5613 | Email: ***@***.******@***.***>


From: Joshua Hiller ***@***.***>
Date: Tuesday, August 30, 2022 at 2:18 AM
To: CrowdStrike/MISP-tools ***@***.***>
Cc: MARONEY, PATRICK ***@***.***>, Author ***@***.***>
Subject: Re: [CrowdStrike/MISP-tools] Duplicative Adversary Records Are Created (Issue #46)

I can't recreate this with the most recent version (the event.info field is compared, with the update being skipped on a match.) I'm worried there's confusion across the disparate branches. Working on aligning these to main and then will ask you to retest.

**Comment by packet-rat** [comment]
FYSA: I have been running v0.6.2
________________________________
