### ISSUE TITLE
Is 'all_indicators' option replaced by '--indicators'?

### ISSUE THREAD

**Issue by cudeso** [CrowdStrike/MISP-tools#66]
Hello,

In the older versions (cs-misp-importer-beta-release-4 etc) there used to be an option `all_indicators`, allowing you to import all indicators, regardless if they are related to a report or not.
I don't see that option in the latest version(s). Is this replaced with `--indicators`?

kind regards,

koen

**Comment by jshcodes** [comment]
Hi @cudeso -

That is correct!  You can use `-i` or `--indicators` to import indicator data.  (You can also achieve this using the `--all` argument, but this will import adversaries and reports first.)
