### ISSUE TITLE
String data, right truncated: 1406 Data too long for column 'content'

### ISSUE THREAD

**Issue by cudeso** [CrowdStrike/MISP-tools#68]
When importing reports this error is raised by MISP (2.4.165)

```
2022-11-21 10:44:41 Error: [PDOException] SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'content' at row 1
Request URL: /events/add
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1132): DboSource->execute()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1942): DboSource->create()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1760): Model->_doSave()
#5 /var/www/MISP/app/Model/EventReport.php(561): Model->save()
#6 /var/www/MISP/app/Model/EventReport.php(114): EventReport->saveAndReturnErrors()
#7 /var/www/MISP/app/Model/Event.php(3687): EventReport->captureReport()
#8 /var/www/MISP/app/Controller/EventsController.php(2214): Event->_add()
#9 [internal function]: EventsController->add()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#13 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#14 {main}
```

**Comment by jshcodes** [comment]
Did you happen to see anything in the import log when this error was generated?

**Comment by cudeso** [comment]
Output from the console (with debug option).
``` 
[2022-11-21 17:13:38,908] DEBUG    processor/thread_1   CSA-221194 Shindig Adds an Extra Unpacking Layer to its Loader and Removes Anti-Analysis Checks in New Update report created.
[2022-11-21 17:13:38,913] DEBUG    processor/thread_1   Retrieved 24 indicators detailed within report CSA-210616
[2022-11-21 17:13:39,408] WARNING  processor/thread_2   Error code 500: An Internal Error Has Occurred.
...
[2022-11-21 17:13:43,797] DEBUG    processor/thread_2   CSIT-22031 Overview of Cyber Activity Surrounding Anniversary of IRGC Leader’s Death; Increase in Iranian Information Operations Capabilities Observed report created.
[2022-11-21 17:13:43,801] DEBUG    processor/thread_2   Retrieved 18 indicators detailed within report CSA-221196
[2022-11-21 17:13:43,882] WARNING  processor/thread_1   Error code 500: An Internal Error Has Occurred.
```

**Comment by jshcodes** [comment]
Does this still occur using the latest release (v0.6.6)?

This feels like a data issue. A couple of possibilities:
- the annotation object (the report's content exceeds the [text field](https://github.com/MISP/misp-objects/blob/main/objects/annotation/definition.json#L44)'s maximum size?) Seems unlikely...
- The call to [add_report_content](https://github.com/CrowdStrike/MISP-tools/blob/main/cs_misp_import/reports.py#L534) (same kind of issue, but a different column).

`CSA-221194` and `CSIT-22031` both import successfully for me when imported into my current test environment (using release v0.6.6), which makes me think there are differences in our database configurations. 

If this still occurs, and you comment out line [534 in cs_misp_import/reports.py](https://github.com/CrowdStrike/MISP-tools/blob/main/cs_misp_import/reports.py#L534) does it go away?

**Comment by jshcodes** [comment]
Follow up: This may be related to the MISP core version, as I was able to generate this error on a different (updated) MISP instance. I will do some more testing to see if I can recreate the problem reliably and address it.

**Comment by jshcodes** [comment]
Not currently able to recreate this using the `0.7.0` source in my environment.  Please reopen this issue or open a new issue if you encounter this again.
