### ISSUE TITLE
"-m, --max_age" deletes all events

### ISSUE THREAD

**Issue by cudeso** [CrowdStrike/MISP-tools#70]
When using `-m 10` all events get deleted on a new install (just imported all adversaries and reports for the last 200 days).

https://github.com/CrowdStrike/MISP-tools/blob/16fde94f3286da014d7bf57fbcd77d31e4643c67/cs_misp_import/importer.py#L199

Maybe switch to `timestamp=["36500d", "{}d".format(max_age)]` instead of the `timestamp=[0, timestamp_max]`?

**Comment by jshcodes** [comment]
Will test this and get it added to our next revision.  Thank you for reporting the issue!  😄

**Comment by jshcodes** [comment]
From what my testing shows, this should work.  Current sprint will move this line to a variation of this change.

**Comment by jshcodes** [comment]
Tweaked this to leverage the `date_to` keyword instead so it aligned to the actual report date.
